---
abstract: 'library for consumers of OpenID identities'
author:
  - 'Brad Fitzpatrick.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OpenID-Consumer
no_index:
  directory:
    - inc
    - t
provides:
  Net::OpenID::ClaimedIdentity:
    file: lib/Net/OpenID/ClaimedIdentity.pm
  Net::OpenID::Consumer:
    file: lib/Net/OpenID/Consumer.pm
    version: 1.05
  Net::OpenID::IndirectMessage:
    file: lib/Net/OpenID/IndirectMessage.pm
  Net::OpenID::URIFetch:
    file: lib/Net/OpenID/URIFetch.pm
  Net::OpenID::URIFetch::Response:
    file: lib/Net/OpenID/URIFetch.pm
  Net::OpenID::VerifiedIdentity:
    file: lib/Net/OpenID/VerifiedIdentity.pm
  Net::OpenID::Yadis:
    file: lib/Net/OpenID/Yadis.pm
    version: 0.05
  Net::OpenID::Yadis::Service:
    file: lib/Net/OpenID/Yadis/Service.pm
  OpenID::util:
    file: lib/Net/OpenID/Consumer.pm
requires:
  Crypt::DH::GMP: 0.0.5
  Digest::SHA1: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Time::Local: 0
  URI: 0
  XML::Simple: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/gugu/net-openid-consumer.git
version: 1.05
